[package]
name = "singh-code-book-decypher"
version = "0.1.0"
authors = ["Rein van 't Veer <reinvantveer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.5"
